apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7a8p
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-7a8p@sha256:2dd4d9cf2eaa26dae1ff7c4287463e7dd083a429bade710c86a0d678624219d9
        name: my-nodejs
        resources: {}
status: {}
